In [133]:
## imports
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [112]:
immport_prefix="/var/datasets/ImmPort/immune_RNAseq/ALLSTUDIES/ALLSTUDIES-DR49.2_Tab/Tab/"

print("STUDY")
print("============================================================")
study = pd.read_table(f"{immport_prefix}/study.txt",sep="\t")
print(study.columns)
print(study.shape)
# study.head()

print("")
print("ARM_OR_COHORT")
print("============================================================")
arm_or_cohort = pd.read_table(f"{immport_prefix}/arm_or_cohort.txt",sep="\t")
print(arm_or_cohort.columns)
print(arm_or_cohort.shape)

print("")
print("ARM_2_SUBJECT")
print("============================================================")
arm_2_subject = pd.read_table(f"{immport_prefix}/arm_2_subject.txt",sep="\t")
print(arm_2_subject.columns)
print(arm_2_subject.shape)

# arm_2_subject.head()

print("")
print("BIOSAMPLE")
print("============================================================")
biosample = pd.read_table(f"{immport_prefix}/biosample.txt",sep="\t")
print(biosample.columns)
print(biosample.shape)

print("============================================================")
lab_test_panel = pd.read_table(f"{immport_prefix}/lab_test_panel.txt",sep="\t")
print(lab_test_panel.columns)
print(lab_test_panel.shape)

print("")
print("LAB_TEST")
print("============================================================")
lab_test = pd.read_table(f"{immport_prefix}/lab_test.txt",sep="\t")
print(lab_test.columns)
print(lab_test.shape)

print("")
print("SUBJECT")
print("============================================================")
subject = pd.read_table(f"{immport_prefix}/subject.txt", sep="\t") 
print(subject.shape)

print("ASSESSMENT_PANEL")
print("============================================================")
assessment_panel = pd.read_table(f"{immport_prefix}/assessment_panel.txt",sep="\t")
print(assessment_panel.columns)
print(assessment_panel.shape)

print("")
print("ASSESSMENT_COMPONENT")
print("============================================================")
assessment_component = pd.read_table(f"{immport_prefix}/assessment_component.txt",sep="\t")
print(assessment_component.columns)
print(assessment_component.shape)

STUDY
============================================================
Index(['STUDY_ACCESSION', 'ACTUAL_COMPLETION_DATE', 'ACTUAL_ENROLLMENT',
       'ACTUAL_START_DATE', 'AGE_UNIT', 'BRIEF_DESCRIPTION', 'BRIEF_TITLE',
       'CLINICAL_TRIAL', 'CONDITION_STUDIED', 'DCL_ID', 'DESCRIPTION', 'DOI',
       'ENDPOINTS', 'GENDER_INCLUDED', 'HYPOTHESIS',
       'INITIAL_DATA_RELEASE_DATE', 'INITIAL_DATA_RELEASE_VERSION',
       'INTERVENTION_AGENT', 'LATEST_DATA_RELEASE_DATE',
       'LATEST_DATA_RELEASE_VERSION', 'MAXIMUM_AGE', 'MINIMUM_AGE',
       'OBJECTIVES', 'OFFICIAL_TITLE', 'SHARED_STUDY',
       'SPONSORING_ORGANIZATION', 'TARGET_ENROLLMENT', 'WORKSPACE_ID'],
      dtype='object')
(811, 28)

ARM_OR_COHORT
============================================================
Index(['ARM_ACCESSION', 'DESCRIPTION', 'NAME', 'STUDY_ACCESSION',
       'TYPE_REPORTED', 'TYPE_PREFERRED', 'WORKSPACE_ID'],
      dtype='object')
(3296, 7)

ARM_2_SUBJECT
============================================================
Index(['ARM_ACCESSION', 'SUBJECT_ACCESSION', 'AGE_EVENT', 'AGE_EVENT_SPECIFY',
       'AGE_UNIT', 'MAX_SUBJECT_AGE', 'MIN_SUBJECT_AGE', 'SUBJECT_PHENOTYPE',
       'SUBJECT_LOCATION', 'MAX_SUBJECT_AGE_IN_YEARS',
       'MIN_SUBJECT_AGE_IN_YEARS'],
      dtype='object')
(99728, 11)

BIOSAMPLE
============================================================

/tmp/ipykernel_21266/869920039.py:29: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  biosample = pd.read_table(f"{immport_prefix}/biosample.txt",sep="\t")

Index(['BIOSAMPLE_ACCESSION', 'DESCRIPTION', 'NAME', 'PLANNED_VISIT_ACCESSION',
       'STUDY_ACCESSION', 'STUDY_TIME_COLLECTED', 'STUDY_TIME_COLLECTED_UNIT',
       'STUDY_TIME_T0_EVENT', 'STUDY_TIME_T0_EVENT_SPECIFY',
       'SUBJECT_ACCESSION', 'SUBTYPE', 'TYPE', 'WORKSPACE_ID'],
      dtype='object')
(482701, 13)
============================================================
Index(['LAB_TEST_PANEL_ACCESSION', 'NAME_PREFERRED', 'NAME_REPORTED',
       'STUDY_ACCESSION', 'WORKSPACE_ID'],
      dtype='object')
(422, 5)

LAB_TEST
============================================================
Index(['LAB_TEST_ACCESSION', 'LAB_TEST_PANEL_ACCESSION', 'BIOSAMPLE_ACCESSION',
       'NAME_PREFERRED', 'NAME_REPORTED', 'REFERENCE_RANGE_ACCESSION',
       'RESULT_UNIT_PREFERRED', 'RESULT_UNIT_REPORTED',
       'RESULT_VALUE_PREFERRED', 'RESULT_VALUE_REPORTED', 'WORKSPACE_ID'],
      dtype='object')
(1279882, 11)

SUBJECT
============================================================

/tmp/ipykernel_21266/869920039.py:48: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  subject = pd.read_table(f"{immport_prefix}/subject.txt", sep="\t")

(94198, 11)
ASSESSMENT_PANEL
============================================================
Index(['ASSESSMENT_PANEL_ACCESSION', 'ASSESSMENT_TYPE', 'NAME_PREFERRED',
       'NAME_REPORTED', 'RESULT_SCHEMA', 'STATUS', 'STUDY_ACCESSION',
       'WORKSPACE_ID'],
      dtype='object')
(729, 8)

ASSESSMENT_COMPONENT
============================================================

/tmp/ipykernel_21266/869920039.py:60: DtypeWarning: Columns (2,8,9,15,16,19,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  assessment_component = pd.read_table(f"{immport_prefix}/assessment_component.txt",sep="\t")

Index(['ASSESSMENT_COMPONENT_ACCESSION', 'AGE_AT_ONSET_PREFERRED',
       'AGE_AT_ONSET_REPORTED', 'AGE_AT_ONSET_UNIT_PREFERRED',
       'AGE_AT_ONSET_UNIT_REPORTED', 'ASSESSMENT_PANEL_ACCESSION',
       'IS_CLINICALLY_SIGNIFICANT', 'LOCATION_OF_FINDING_PREFERRED',
       'LOCATION_OF_FINDING_REPORTED', 'NAME_PREFERRED', 'NAME_REPORTED',
       'ORGAN_OR_BODY_SYSTEM_PREFERRED', 'ORGAN_OR_BODY_SYSTEM_REPORTED',
       'PLANNED_VISIT_ACCESSION', 'REFERENCE_RANGE_ACCESSION',
       'RESULT_UNIT_PREFERRED', 'RESULT_UNIT_REPORTED',
       'RESULT_VALUE_CATEGORY', 'RESULT_VALUE_PREFERRED',
       'RESULT_VALUE_REPORTED', 'STUDY_DAY', 'SUBJECT_ACCESSION',
       'SUBJECT_POSITION_PREFERRED', 'SUBJECT_POSITION_REPORTED',
       'TIME_OF_DAY', 'VERBATIM_QUESTION', 'WHO_IS_ASSESSED', 'WORKSPACE_ID'],
      dtype='object')
(2093159, 28)

In [113]:
#Helper methods
def lab_test_panels_by_study(study_accession,lab_tests):
    study_lab_tests = lab_tests[lab_tests['STUDY_ACCESSION']==study_accession]
    study_panels = study_lab_tests[['PANEL_NAME','LAB_TEST_NAME']]
    study_panels = study_panels.groupby(['PANEL_NAME','LAB_TEST_NAME']).size().reset_index(name="COUNTS")
    return study_panels
def assessment_panels_by_study(study_accession,assessments):
    study_assessments = assessments[assessments['STUDY_ACCESSION']==study_accession]
    study_panels = study_assessments[['PANEL_NAME','COMPONENT_NAME']]
    study_panels = study_panels.groupby(['PANEL_NAME','COMPONENT_NAME']).size().reset_index(name="COUNTS")
    return study_panels

In [114]:
## How many Labtests
print(f'Labtests amount: {lab_test.drop_duplicates().shape}')
print(f'Labtest panels amount: {lab_test_panel.drop_duplicates().shape}')

## How many Subjects
print(f'Subject amount: {subject.drop_duplicates().shape}')
## How many Studies
print(f'Studies amount: {study.drop_duplicates().shape}')

## Labtests: "Biomarkers", welche

Labtests amount: (1279882, 11)
Labtest panels amount: (422, 5)
Subject amount: (94198, 11)
Studies amount: (811, 28)

In [115]:
lab_test_panel = lab_test_panel.rename(columns={'NAME_REPORTED': 'PANEL_NAME'})
lab_test = lab_test.rename(columns={'NAME_REPORTED': 'LAB_TEST_NAME'})
lab_tests = pd.merge(lab_test_panel,lab_test,
                    left_on='LAB_TEST_PANEL_ACCESSION',right_on='LAB_TEST_PANEL_ACCESSION') 
lab_test.head()

,LAB_TEST_ACCESSION,LAB_TEST_PANEL_ACCESSION,BIOSAMPLE_ACCESSION,NAME_PREFERRED,LAB_TEST_NAME,REFERENCE_RANGE_ACCESSION,RESULT_UNIT_PREFERRED,RESULT_UNIT_REPORTED,RESULT_VALUE_PREFERRED,RESULT_VALUE_REPORTED,WORKSPACE_ID
0,LT1,LP581,BS235842,White Blood Cell Count,WBC,RR81,NaN,10*3 cells/uL,8.5,8.5 10*3 cells/uL,990
1,LT10,LP581,BS235842,Eosinophils,EOSINOPHILS,RR13,percentage,%,1.0,1 %,990
2,LT100,LP581,BS235844,"Neutrophils, Segmented",SEGMENTED NEUTROPHILS,RR75,percentage,%,53.0,53 %,990
3,LT1000,LP581,BS236373,Basophils,BASOPHILS,RR5,percentage,%,0.0,0 %,990
4,LT10000,LP581,BS236064,Lymphocyte,LYMPHOCYTES,RR35,percentage,%,26.0,26 %,990

In [121]:
lab_tests = pd.merge(lab_test_panel,lab_test,
                    left_on='LAB_TEST_PANEL_ACCESSION',right_on='LAB_TEST_PANEL_ACCESSION')
print(lab_tests.shape)
lab_tests_backup = lab_tests.copy(deep=True)
lab_tests.head()

(1279882, 15)

,LAB_TEST_PANEL_ACCESSION,NAME_PREFERRED_x,PANEL_NAME,STUDY_ACCESSION,WORKSPACE_ID_x,LAB_TEST_ACCESSION,BIOSAMPLE_ACCESSION,NAME_PREFERRED_y,LAB_TEST_NAME,REFERENCE_RANGE_ACCESSION,RESULT_UNIT_PREFERRED,RESULT_UNIT_REPORTED,RESULT_VALUE_PREFERRED,RESULT_VALUE_REPORTED,WORKSPACE_ID_y
0,LP10000,Chemistry Test,CHEMISTRY,SDY354,3709,LT100000,BS727101,Uric Acid,H_URIC (URATE),NaN,mg/dl,MG/DL,12.0,12 MG/DL,3709
1,LP10000,Chemistry Test,CHEMISTRY,SDY354,3709,LT100004,BS727102,Blood Urea Nitrogen,H_BUN (BUN),NaN,mg/dl,MG/DL,24.0,24 MG/DL,3709
2,LP10000,Chemistry Test,CHEMISTRY,SDY354,3709,LT100017,BS727106,Uric Acid,H_URIC (URATE),NaN,mg/dl,MG/DL,5.4,5.4 MG/DL,3709
3,LP10000,Chemistry Test,CHEMISTRY,SDY354,3709,LT100018,BS727106,Blood Urea Nitrogen,H_BUN (BUN),NaN,mg/dl,MG/DL,29.0,29 MG/DL,3709
4,LP10000,Chemistry Test,CHEMISTRY,SDY354,3709,LT100031,BS727110,Blood Urea Nitrogen,H_BUN (BUN),NaN,mg/dl,MG/DL,17.0,17 MG/DL,3709

In [122]:
#Helper methods
def lab_test_panels(lab_tests):
    study_panels = lab_tests[['PANEL_NAME','LAB_TEST_NAME']]
    study_panels = study_panels.groupby(['PANEL_NAME','LAB_TEST_NAME']).size().reset_index(name="COUNTS")
    return study_panels
def lab_test_panels_prefered_names(lab_tests):
    study_panels = lab_tests[['NAME_PREFERRED_x','NAME_PREFERRED_y']]
    study_panels = study_panels.groupby(['NAME_PREFERRED_x','NAME_PREFERRED_y']).size().reset_index(name="COUNTS")
    return study_panels

lab_tests_PANEL_NAME = lab_test_panels(lab_tests)
lab_tests_NAME_PREFERRED = lab_test_panels_prefered_names(lab_tests)
PANEL_NAMEs_unique = lab_tests_PANEL_NAME['PANEL_NAME'].unique()
LAB_TESTS_unique = lab_tests_PANEL_NAME['LAB_TEST_NAME'].unique()
NAME_PREFERRED_x_unique = lab_tests_NAME_PREFERRED['NAME_PREFERRED_x'].unique()
NAME_PREFERRED_y_unique = lab_tests_NAME_PREFERRED['NAME_PREFERRED_y'].unique()


print('PANEL_NAMEs '  + str(len(PANEL_NAMEs_unique)))
print('LAB_TESTS '  + str(len(LAB_TESTS_unique)))
print('LAB_TEST counts: ' + str(sum(lab_tests_PANEL_NAME['COUNTS'])))
print('PANEL_NAMEs preferred names '  + str(len(NAME_PREFERRED_x_unique)))
print('LAB_TESTS preferred names '  + str(len(NAME_PREFERRED_y_unique)))
print('LAB_TEST preferred counts: ' + str(sum(lab_tests_NAME_PREFERRED['COUNTS'])))


lab_tests_PANEL_NAME.head()

PANEL_NAMEs 105
LAB_TESTS 1550
LAB_TEST counts: 1279882
PANEL_NAMEs preferred names 17
LAB_TESTS preferred names 185
LAB_TEST preferred counts: 802211

,PANEL_NAME,LAB_TEST_NAME,COUNTS
0,AD5 neutralizing antibody titer,pre-existing serum ad5 neutralizing antibody t...,20
1,AFP (alpha-fetoprotein),AFP (alpha-fetoprotein),56
2,Act CD8 T Cell Response,Act CD8 T Cell Response,25
3,Amniotic Fluid Panel,Glucose,15
4,Amniotic Fluid Panel,Interleukin 6,15

In [123]:
print('NA NAME_PREFERRED_x: ' + str(lab_tests['NAME_PREFERRED_x'].isna().sum()))
print('NA NAME_PREFERRED_y: ' + str(lab_tests['NAME_PREFERRED_y'].isna().sum()))
print('NA PANEL_NAME: ' + str(lab_tests['PANEL_NAME'].isna().sum()))
print('NA LAB_TEST_NAME: ' + str(lab_tests['LAB_TEST_NAME'].isna().sum()))

NA NAME_PREFERRED_x: 340701
NA NAME_PREFERRED_y: 297137
NA PANEL_NAME: 0
NA LAB_TEST_NAME: 0

In [ ]:
lab_tests

,LAB_TEST_PANEL_ACCESSION,NAME_PREFERRED_x,PANEL_NAME,STUDY_ACCESSION,WORKSPACE_ID_x,LAB_TEST_ACCESSION,BIOSAMPLE_ACCESSION,NAME_PREFERRED_y,LAB_TEST_NAME,REFERENCE_RANGE_ACCESSION,RESULT_UNIT_PREFERRED,RESULT_UNIT_REPORTED,RESULT_VALUE_PREFERRED,RESULT_VALUE_REPORTED,WORKSPACE_ID_y
0,LP10000,Chemistry Test,CHEMISTRY,SDY354,3709,LT100000,BS727101,Uric Acid,H_URIC (URATE),NaN,mg/dl,MG/DL,12.0,12 MG/DL,3709
1,LP10000,Chemistry Test,CHEMISTRY,SDY354,3709,LT100004,BS727102,Blood Urea Nitrogen,H_BUN (BUN),NaN,mg/dl,MG/DL,24.0,24 MG/DL,3709
2,LP10000,Chemistry Test,CHEMISTRY,SDY354,3709,LT100017,BS727106,Uric Acid,H_URIC (URATE),NaN,mg/dl,MG/DL,5.4,5.4 MG/DL,3709
3,LP10000,Chemistry Test,CHEMISTRY,SDY354,3709,LT100018,BS727106,Blood Urea Nitrogen,H_BUN (BUN),NaN,mg/dl,MG/DL,29.0,29 MG/DL,3709
4,LP10000,Chemistry Test,CHEMISTRY,SDY354,3709,LT100031,BS727110,Blood Urea Nitrogen,H_BUN (BUN),NaN,mg/dl,MG/DL,17.0,17 MG/DL,3709
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1279877,LP7145,Chemistry Test,BASIC_CHEMISTRY,SDY352,3709,LT91166,BS723884,Bilirubin,TBILI (BILI),NaN,mg/dl,MG/DL,0.5,0.5 MG/DL,3709
1279878,LP7145,Chemistry Test,BASIC_CHEMISTRY,SDY352,3709,LT91167,BS723884,Potassium,POTASS (K),NaN,NaN,MEQ/L,3.2,3.2 MEQ/L,3709
1279879,LP7145,Chemistry Test,BASIC_CHEMISTRY,SDY352,3709,LT91168,BS723884,Carbon Dioxide,CO2 (CO2),NaN,NaN,MEQ/L,25.0,25 MEQ/L,3709
1279880,LP7145,Chemistry Test,BASIC_CHEMISTRY,SDY352,3709,LT91169,BS723884,BUN,BUN (BUN),NaN,mg/dl,MG/DL,45.0,45 MG/DL,3709
1279881,LP7145,Chemistry Test,BASIC_CHEMISTRY,SDY352,3709,LT91170,BS723884,Magnesium,MG (MG),NaN,mg/dl,MG/DL,1.2,1.2 MG/DL,3709

In [134]:
grouped = lab_tests_PANEL_NAME.groupby('PANEL_NAME')['LAB_TEST_NAME'].apply(list).reset_index()
for index, row in grouped.iterrows():
    group = row['PANEL_NAME']
    pref_name = lab_tests[lab_tests['PANEL_NAME'] == group]['NAME_PREFERRED_x']
    if isinstance(pref_name, np.ndarray) and len(pref_name) > 0:
        print(pref_name)
        pref_name = pref_name[0]
    else: 
        pref_name = ''
        
    items = '\n\t'.join(row['LAB_TEST_NAME'])
    pref_item = {}
    for i, x in enumerate(items):
        y = lab_tests[lab_tests['LAB_TEST_NAME'] == x]['NAME_PREFERRED_y']
        if len(y) > 0:
            pref_item[i] = y
        else:
            pref_item[i] = ''
    
    print(f"\n{group} ({pref_name})")
    [print('\t' + str(x) + f' ({pref_item[i]})') for i, x in enumerate(row['LAB_TEST_NAME'])]

AD5 neutralizing antibody titer ()
	pre-existing serum ad5 neutralizing antibody titer ()

AFP (alpha-fetoprotein) ()
	AFP (alpha-fetoprotein) ()

Act CD8 T Cell Response ()
	Act CD8 T Cell Response ()

Amniotic Fluid Panel ()
	Glucose ()
	Interleukin 6 ()
	Lactate Dehydrogenase ()
	White Blood Count ()

Anti-HBc IgM ()
	Anti-HBc IgM ()

Antibodies against Plasmodium falciparum antigens ()
	Antibodies against PfAMA-1 ()
	Antibodies against PfCSP ()
	Antibodies against PfEXP-1 ()
	Antibodies against PfLSA-1 ()
	Antibodies against PfMSP-1 ()
	Antibodies against PfMSP-5 ()
	Antibodies against PfSSP2 ()

Antibody Titers ()
	Anti-Diptheria ()
	Anti-Hepatitis A ()
	Anti-Hepatitis B ()
	Anti-Tetanus ()

Autoantibodies ()
	Anti-Double Stranded DNA ()
	Anti-GAD65 ()
	Anti-ICA512 ()
	Anti-Insulin ()
	Antinuclear Antibodies ()
	Cyclic Citrullinated Peptide Antibody ()
	Rheumatoid Factor ()

Autoimmune Liver Disease ()
	Anti-Smooth-Muscle Antibody ()
	Anti-liver-kidney microsome antibody ()
	Antimitochondrial Antibodies ()
	Antinuclear Antibodies ()
	Immunoglobulin G ()

KeyboardInterrupt:

In [ ]:
### manually assigned by oreferred names -> macht kein sinn weil da extrem viele nans sind-..
#### ASSIGNEMENT BY PANEL_NAMES

### cell types
cell_type_PANEL_NAMEs = [
    'Blood Cell Count: ',
    'Blood Cell Count with Differential: ',
    'Blood cell counts: ',
    'CBC: ',
    'CBC/Differential Results: ',
    'CBC_DIFFERENTIAL: ',
    'CBC_Results: ',
    'Complete Blood Cell Count: ',
    'Complete blood count: ',
    'DIFFERENTIAL: ',
    'HEMATOLOGY: ',
    'Hematology',
    'Hematology test: ',
]

### biomarkers
biomarker_PANEL_NAMEs = [
    'Blood Flow Cytometry: ',
    'Protein or Enzyme Type Measurement: ',
    ]

# ### Fasting
# FASTING_BLOOD_CHEMISTRY
# Fasting Lipid Panel: 
# Fasting Lipid Profile: 
# Fasting Lipids: 


# ### antigens
# Basophil
# Immunology Test: 
# Serum Protein Electrophoresis: 


# ### chemistry
# BASIC_CHEMISTRY
# BLOOD_CHEMISTRY
# Blood Chemistry: 
# Blood Chemistry Measurement: 
# Blood Chemistry Test: 
# Chemistry Test: 
# Clinical Chemistry: 
# Comprehensive Metabolic Panel: 
# Hematology
# Serum Chemistry: 


# ### creatinin
# Creatinine test: 
# Protein or Enzyme Type Measurement: 

# SERUM_CREATININE: 


# ### other

# ### urea
# Urinalysis: 
# Urine

# ### liver
# LIVER_PANEL:

In [ ]:
biomarker_PANEL_NAMEs = [string[:-2] for string in biomarker_PANEL_NAMEs]
# lab_tests.iloc[0]['PANEL_NAME'] 
test = lab_tests[lab_tests['PANEL_NAME'] == 'Basophil']
test

Empty DataFrame
Columns: [LAB_TEST_PANEL_ACCESSION, NAME_PREFERRED_x, PANEL_NAME, STUDY_ACCESSION, WORKSPACE_ID_x, LAB_TEST_ACCESSION, BIOSAMPLE_ACCESSION, NAME_PREFERRED_y, LAB_TEST_NAME, REFERENCE_RANGE_ACCESSION, RESULT_UNIT_PREFERRED, RESULT_UNIT_REPORTED, RESULT_VALUE_PREFERRED, RESULT_VALUE_REPORTED, WORKSPACE_ID_y]
Index: []

In [ ]:
PANEL_NAMEs_unique

array(['AD5 neutralizing antibody titer', 'AFP (alpha-fetoprotein)',
       'Act CD8 T Cell Response', 'Amniotic Fluid Panel', 'Anti-HBc IgM',
       'Antibodies against Plasmodium falciparum antigens',
       'Antibody Titers', 'Autoantibodies', 'Autoimmune Liver Disease',
       'BASIC_CHEMISTRY', 'BLOOD_CHEMISTRY', 'Basophil',
       'Blood Cell Count', 'Blood Cell Count with Differential',
       'Blood Cell Measurement', 'Blood Chemistry',
       'Blood Chemistry Measurement', 'Blood Chemistry Test',
       'Blood Flow Cytometry', 'Blood Smear', 'Blood cell counts', 'CBC',
       'CBC/Differential Results', 'CBC_DIFFERENTIAL', 'CBC_Results',
       'CHEMISTRY', 'CMV Screen and Titer', 'CMV Serology',
       'CMV and EBV serology', 'Calcium test', 'Chemistry Test',
       'Clinical Chemistry', 'Coagulation', 'Coagulation Status',
       'Complete Blood Cell Count', 'Complete blood count',
       'Comprehensive Metabolic Panel', 'Creatinine test', 'DIFFERENTIAL',
       'Diagnostic Immunology', 'Diagnostic laboratory data',
       'Endocrinology', 'Enzyme measurement', 'FASTING_BLOOD_CHEMISTRY',
       'Fasting Lipid Panel', 'Fasting Lipid Profile', 'Fasting Lipids',
       'HBV/HCV Infection Status', 'HEMATOLOGY', 'HIV serology',
       'HRV PCR', 'Hb type by BioRad D-10', 'Hematology',
       'Hematology test', 'Hemoglobin from blood', 'Hormone measurement',
       'IgE', 'IgE/RAST', 'Immune System Measurement', 'Immunology',
       'Immunology Test', 'Immunology laboratory test', 'LIVER_FUNCTION',
       'LIVER_PANEL', 'LPS quantification', 'Lab Test for Blood Samples',
       'Laboratory test related to hemostasis', 'Malaria Infection',
       'Metabolic Assessments', 'Metabolic Panel', 'Microbial Evaluation',
       'Mixed-Meal Tolerance Test', 'Molecular Diagnostics',
       'Nasal Lavage Fluid Cell Counts', 'Parathyroid test',
       'Pf Density by microscopy blood smear',
       'Pf Density by qPCR of blood', 'Pf presence by blood PCR',
       'Pregnancy test', 'Previous staphylococcus aureus culture',
       'Protein measurement', 'Protein or Enzyme Type Measurement',
       'RA_Lab_Panel', 'RENAL_PANEL', 'RV16 QPCR  (RV1A16 P&P)',
       'Radiation exposure', 'Recipient CMV and EBV Serologies',
       'Recipient CMV, EBV, BKV by PCR', 'Renal Function Test',
       'Respiratory Viral Panel', 'SARS-CoV-2 PCR', 'SERUM_CREATININE',
       'Serology', 'Serum Chemistries', 'Serum Chemistry',
       'Serum Protein Electrophoresis', 'Thyroid Panel', 'Total IgE',
       'Urinalysis', 'Urine', 'Vaccine Antibody Titers', 'Vitamin D test',
       'Vitamin measurement', 'serum antibody level', 'urine microscopy'],
      dtype=object)

In [ ]:
lab_tests.iloc[0]['PANEL_NAME']

'Amniotic Fluid Panel: '

lab_tests.head()

In [ ]:
lab_tests.head()

,LAB_TEST_PANEL_ACCESSION,NAME_PREFERRED_x,PANEL_NAME,STUDY_ACCESSION,WORKSPACE_ID_x,LAB_TEST_ACCESSION,BIOSAMPLE_ACCESSION,NAME_PREFERRED_y,LAB_TEST_NAME,REFERENCE_RANGE_ACCESSION,RESULT_UNIT_PREFERRED,RESULT_UNIT_REPORTED,RESULT_VALUE_PREFERRED,RESULT_VALUE_REPORTED,WORKSPACE_ID_y
0,LP10000,Chemistry Test,Amniotic Fluid Panel:,SDY354,3709,LT100000,BS727101,Uric Acid,H_URIC (URATE),NaN,mg/dl,MG/DL,12.0,12 MG/DL,3709
1,LP10000,Chemistry Test,Amniotic Fluid Panel:,SDY354,3709,LT100004,BS727102,Blood Urea Nitrogen,H_BUN (BUN),NaN,mg/dl,MG/DL,24.0,24 MG/DL,3709
2,LP10000,Chemistry Test,Amniotic Fluid Panel:,SDY354,3709,LT100017,BS727106,Uric Acid,H_URIC (URATE),NaN,mg/dl,MG/DL,5.4,5.4 MG/DL,3709
3,LP10000,Chemistry Test,Amniotic Fluid Panel:,SDY354,3709,LT100018,BS727106,Blood Urea Nitrogen,H_BUN (BUN),NaN,mg/dl,MG/DL,29.0,29 MG/DL,3709
4,LP10000,Chemistry Test,Amniotic Fluid Panel:,SDY354,3709,LT100031,BS727110,Blood Urea Nitrogen,H_BUN (BUN),NaN,mg/dl,MG/DL,17.0,17 MG/DL,3709