In [1]:
## imports
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
immport_prefix="/var/datasets/ImmPort/immune_RNAseq/ALLSTUDIES/ALLSTUDIES-DR49.2_Tab/Tab/"


print("WORKSPACE")
print("============================================================")
workspace = pd.read_table(f"{immport_prefix}/workspace.txt",sep="\t")
print(workspace.columns)
print(workspace.shape)


### contains elinks
print("lk_exp_measurement_tech")
print("============================================================")
lk_exp_measurement_tech = pd.read_table(f"{immport_prefix}/lk_exp_measurement_tech.txt",sep="\t")
print(lk_exp_measurement_tech.columns)
print(lk_exp_measurement_tech.shape)

print("EXPERIMENT")
print("============================================================")
experiment = pd.read_table(f"{immport_prefix}/experiment.txt",sep="\t")
print(experiment.columns)
print(experiment.shape)
experiment.head()

lk_exp_measurement_tech.head()

WORKSPACE
============================================================
Index(['WORKSPACE_ID', 'CATEGORY', 'NAME', 'TYPE'], dtype='object')
(163, 4)
lk_exp_measurement_tech
============================================================
Index(['NAME', 'DESCRIPTION', 'LINK'], dtype='object')
(92, 3)
EXPERIMENT
============================================================
Index(['EXPERIMENT_ACCESSION', 'DESCRIPTION', 'MEASUREMENT_TECHNIQUE', 'NAME',
       'STUDY_ACCESSION', 'WORKSPACE_ID'],
      dtype='object')
(3047, 6)

,NAME,DESCRIPTION,LINK
0,Fluorescent Antibody Procedure,An immunological procedure in which the antibo...,http://purl.obolibrary.org/obo/NCIT_C17370
1,Neuraminidase Inhibition Assay,A type of enzyme-based assay that assesses neu...,http://purl.obolibrary.org/obo/NCIT_C120696
2,Microneutralization Assay,An in vitro assay that is used to determine wh...,http://purl.obolibrary.org/obo/NCIT_C120695
3,Bulk RNA-seq assay,An RNA-seq assay in which the sample that is s...,http://purl.obolibrary.org/obo/OBI_0003090
4,1D Gel,One dimensional gels are used to separate an a...,http://purl.obolibrary.org/obo/OBI_0001121

In [3]:
print("EXPSAMPLE_PLUBLIC_REPOSITORY")
print("============================================================")
gene_expression = pd.read_table(f"{immport_prefix}/expsample_public_repository.txt",sep="\t")
print(gene_expression.columns)
print(gene_expression.shape)

print("EXPSAMPLE")
print("============================================================")
expsample = pd.read_table(f"{immport_prefix}/expsample.txt",sep="\t")
print(expsample.columns)
print(expsample.shape)

print("EXPERIMENT")
print("============================================================")
experiment = pd.read_table(f"{immport_prefix}/experiment.txt",sep="\t")
print(experiment.columns)
print(experiment.shape)

EXPSAMPLE_PLUBLIC_REPOSITORY
============================================================
Index(['RESULT_ID', 'EXPSAMPLE_ACCESSION', 'REPOSITORY_ACCESSION',
       'REPOSITORY_NAME'],
      dtype='object')
(52404, 4)
EXPSAMPLE
============================================================
Index(['EXPSAMPLE_ACCESSION', 'DESCRIPTION', 'EXPERIMENT_ACCESSION', 'NAME',
       'RESULT_SCHEMA', 'UPLOAD_RESULT_STATUS', 'WORKSPACE_ID'],
      dtype='object')
(850798, 7)
EXPERIMENT
============================================================
Index(['EXPERIMENT_ACCESSION', 'DESCRIPTION', 'MEASUREMENT_TECHNIQUE', 'NAME',
       'STUDY_ACCESSION', 'WORKSPACE_ID'],
      dtype='object')
(3047, 6)

In [4]:
expsample[expsample['EXPSAMPLE_ACCESSION']=='ES769464']

,EXPSAMPLE_ACCESSION,DESCRIPTION,EXPERIMENT_ACCESSION,NAME,RESULT_SCHEMA,UPLOAD_RESULT_STATUS,WORKSPACE_ID
674909,ES769464,NaN,EXP13591,NaN,OTHER,Not_Parsed,2799

In [23]:
experiment[experiment['EXPERIMENT_ACCESSION']=='EXP4018']

,EXPERIMENT_ACCESSION,DESCRIPTION,MEASUREMENT_TECHNIQUE,NAME,STUDY_ACCESSION,WORKSPACE_ID
2471,EXP4018,Microarray experiment to define the transcript...,Transcription profiling by array,Experiment - Gene Chip Analysis,SDY33,3

In [25]:
expsample_gene_expr = pd.merge(gene_expression, expsample, on='EXPSAMPLE_ACCESSION', how='inner')
experiment_sample_gene_expr = pd.merge(expsample_gene_expr, experiment, on='EXPERIMENT_ACCESSION', how='outer')
print(experiment_sample_gene_expr.shape)
experiment_sample_gene_expr.head()

(55225, 15)

,RESULT_ID,EXPSAMPLE_ACCESSION,REPOSITORY_ACCESSION,REPOSITORY_NAME,DESCRIPTION_x,EXPERIMENT_ACCESSION,NAME_x,RESULT_SCHEMA,UPLOAD_RESULT_STATUS,WORKSPACE_ID_x,DESCRIPTION_y,MEASUREMENT_TECHNIQUE,NAME_y,STUDY_ACCESSION,WORKSPACE_ID_y
0,1.0,ES776590,GSM1422023,GEO,cRNA27760 Positive for globin peak,EXP13635,5920711019_C,PUBLIC REPOSITORY,Parsed,2883.0,Raw (non-normalized) Illumina data; mapping be...,Transcription profiling by array,Gene expression measurement on 2010 subjects a...,SDY311,2883
1,2.0,ES776602,GSM1422046,GEO,cRNA27783 Positive for globin peak,EXP13635,5920834001_E,PUBLIC REPOSITORY,Parsed,2883.0,Raw (non-normalized) Illumina data; mapping be...,Transcription profiling by array,Gene expression measurement on 2010 subjects a...,SDY311,2883
2,3.0,ES776615,GSM1422059,GEO,cRNA27796 Positive for globin peak,EXP13635,5920666013_E,PUBLIC REPOSITORY,Parsed,2883.0,Raw (non-normalized) Illumina data; mapping be...,Transcription profiling by array,Gene expression measurement on 2010 subjects a...,SDY311,2883
3,4.0,ES776617,GSM1422061,GEO,cRNA27798 Positive for globin peak,EXP13635,5920666014_C,PUBLIC REPOSITORY,Parsed,2883.0,Raw (non-normalized) Illumina data; mapping be...,Transcription profiling by array,Gene expression measurement on 2010 subjects a...,SDY311,2883
4,5.0,ES776625,GSM1422069,GEO,cRNA27806 Positive for globin peak,EXP13635,5920666014_K,PUBLIC REPOSITORY,Parsed,2883.0,Raw (non-normalized) Illumina data; mapping be...,Transcription profiling by array,Gene expression measurement on 2010 subjects a...,SDY311,2883

In [29]:
experiment_sample_gene_expr[experiment_sample_gene_expr['EXPERIMENT_ACCESSION']=='EXP13377']

,RESULT_ID,EXPSAMPLE_ACCESSION,REPOSITORY_ACCESSION,REPOSITORY_NAME,DESCRIPTION_x,EXPERIMENT_ACCESSION,NAME_x,RESULT_SCHEMA,UPLOAD_RESULT_STATUS,WORKSPACE_ID_x,DESCRIPTION_y,MEASUREMENT_TECHNIQUE,NAME_y,STUDY_ACCESSION,WORKSPACE_ID_y
52557,NaN,NaN,NaN,NaN,NaN,EXP13377,NaN,NaN,NaN,NaN,BAM files for EXP1377 and EXP14625 RNA Seq res...,RNA sequencing,RNA Seq Batch 1,SDY67,2510

In [27]:
### RNAseq whole blood
# experiment_sample_gene_expr[experiment_sample_gene_expr['STUDY_ACCESSION']=='SDY1412']['REPOSITORY_ACCESSION'].unique() ###GPL16791	Illumina HiSeq 2500 (Homo sapiens)
#experiment_sample_gene_expr[experiment_sample_gene_expr['STUDY_ACCESSION']=='SDY1092']['REPOSITORY_ACCESSION'].unique() ###GPL11154	Illumina HiSeq 2000 (Homo sapiens)
#experiment_sample_gene_expr[experiment_sample_gene_expr['STUDY_ACCESSION']=='SDY1172']['REPOSITORY_ACCESSION'].unique() ###GPL11154	Illumina HiSeq 2000 (Homo sapiens)
#experiment_sample_gene_expr[experiment_sample_gene_expr['STUDY_ACCESSION']=='SDY1381']['REPOSITORY_ACCESSION'].unique() ###GPL11154	Illumina HiSeq 2000 (Homo sapiens)
### RNAseq PBMC -> TODO hat keine Repository ID ? wtf... 
### fokus auf whole blood... 
experiment_sample_gene_expr[experiment_sample_gene_expr['STUDY_ACCESSION']=='SDY67']['REPOSITORY_ACCESSION'].unique() ### 
#experiment_sample_gene_expr[experiment_sample_gene_expr['EXPSAMPLE_ACCESSION']=='ES769464']['REPOSITORY_ACCESSION'].unique() ### 
### nope, but in immport NGS.PTL5892.docx    -> Illumina HiSeq 2000 (Homo sapiens)
#### Microarray whole blood:

array([nan], dtype=object)

In [ ]:
#### Function that gives me the platform info for my study. 
from Bio import Entrez

def get_platform_info(accession_numbers):
    Entrez.email = 'elias.schreiner@uni-tuebingen.de'
    for accession in accession_numbers:
        handle = Entrez.esearch(db="gds", term=accession)
        record = Entrez.read(handle)
        if record["IdList"]:
            gds_id = record["IdList"][0]
            handle = Entrez.efetch(db="gds", id=gds_id, retmode="xml")
            records = Entrez.read(handle)
            for record in records:
                platform = record["Platform_id"]
                title = record["title"]
                print(f"Accession: {accession}, Platform: {platform}, Title: {title}")
        else:
            print(f"No information found for accession: {accession}")

# Example usage:
accession_numbers = ["GSM1234567", "GSM9876543"]
get_platform_info(accession_numbers)

StreamModeError: the XML file must be opened in binary mode.